- name: Build and Export
  run: npm run build

- name: Deploy to Azure Web App
  uses: azure/webapps-deploy@v2
  with:
    app-name: AzureWebApp-1
    publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
    package: ./out
